// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqoeqezavgriiyjcmhoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxb2VxZXphdmdyaWl5amNtaG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MTY1NjUsImV4cCI6MjA4ODA5MjU2NX0.h4WCUd1NiBsPtYMutnkVIUs6VWiPiIBxNwJrb153r3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});